package produtos.apps.unitario.objetos;

import java.util.LinkedHashMap;

public class AppsSolicitarAvaliacao {
    public static String appsSolicitarAvaliacaoTitle = "//div[contains(text(), \"Solicitar avaliação\")]";
    public static String appsTipoAvaliacaoCombobox = "//select[@ng-model=\"ctrl.valuation.valuation_type_id\"]";
    public static String appsAvaliadorResponsavelCombobox = "//select[@ng-model=\"ctrl.valuation.valuer_id\"]";
    public static String appsNomeDoClienteInput = "//input[@ng-model=\"ctrl.valuation.name\"]";
    public static String appsAnoDeInteresseInput = "//input[@ng-model=\"ctrl.interest.year\"]";
    public static String appsCelularInput = "//input[@ng-model=\"ctrl.valuation.cell_phone\"]";
    public static String appsPlacaInput = "//input[@ng-model=\"ctrl.valuation.plate\"]";
    public static String appsSolicitarButton = "//button[@ng-click=\"ctrl.solicita()\"]";
    public static String appsBuscarPlacaButton = "//button[@ng-click=\"ctrl.getPlateData()\"]";
    public static String appsVeiculoInput = "//av-search-filter[@label=\"Veículo\"][contains(@controller, \"oraculo/versions/listAll\")]//input[@placeholder=\"Todos\"]";
    public static String appsPrimeiroVeiculoLi = "//av-search-filter[@label=\"Veículo\"][contains(@controller, \"oraculo/versions/listAll\")]//li/a";
    public static String appsObrigatoriedadeTipoDeAvaliacaoText = "//div[text()=\"É necessário selecionar um TIPO DE AVALIAÇÃO!\"]";
    public static String appsObrigatoriedadeAvaliadorResponsavelText = "//div[text()=\"É necessário selecionar um AVALIADOR RESPONSÁVEL!\"]";
    public static String appsObrigatoriedadeNomeText = "//div[text()=\"É necessário digitar uma valor para: NOME!\"]";
    public static String appsObrigatoriedadeCelularText = "//div[text()=\"É necessário digitar uma valor para: CELULAR!\"]";
    public static String appsObrigatoriedadePlacaText = "//div[text()=\"É necessário digitar uma valor para: PLACA!\"]";
    public static String appsPlacaInvalidaText = "//div[text()=\"Por favor informe uma PLACA válida!\"]";
    public static String appsSolicitarAvaliacoSolicitarButton = "//button[@class=\"btn btn-success m-sm text-uppercase ng-binding\"]";
    public static String appsSolicitarAvaliacaoRenavamInput = "//input[@ng-model=\"ctrl.valuation.renavam\"]";
    public static String appsSolicitarAvaliacaoChaveReservaSelect = "//label[contains(.,\"O veículo possui chave reserva?\")]/following-sibling::select[@class]";
    public static String appsSolicitarAvaliacaoManualSelect = "//label[contains(.,\"Tem manual?\")]/following-sibling::select[@class]";
    public static String appsSolicitarAvaliacaoSolicitaButton = "//button[@ng-click=\"ctrl.solicita()\"]";
    public static String appsPlacaNaoEncontradaText = "//div[text()=\"Placa não encontrada!\"]";
    public static String appsSolicitarAvaliacaoCPFInput = "//div[@class=\"row mt-sm\"]//div[@class=\"col-lg-4 col-sm-4 mb-lg\"]//input[@class=\"form-control ng-pristine ng-untouched ng-valid ng-empty ng-valid-cpf ng-valid-cnpj\"]";
    public static String appsSolicitarAvaliacaoExpectativaDoClienteInput = "//input[@ng-model=\"ctrl.valuation.expected_value\"]";
    public static String appsSolicitarAvaliacaoOpenFieldObsButton = "//i[@class=\"fa fa-arrow-down\"]";
    public static String appsSolicitarAvaliacaoTextObsInput = "//textarea[@class=\"form-control note-editor ng-pristine ng-untouched ng-valid ng-empty\"]";
    public static String appsSolicitarAvaliacaoNumeroTelefoneInput = "//input[@class=\"form-control phone_mask\"]";
    public static String appsSolicitarAvaliacaoEmailClienteInput = "//input[@ng-model=\"ctrl.valuation.email\"]";
    public static String appsSolicitarAvaliacaoAndretaCPFInput = "//div[@ng-show=\"ctrl.$api.showFields.cpf_cnpj && !($root.configKeyExists('dataprovider:use:bci'))\"]//input";
    public static String appsSolicitarAvaliacaoEmailInput = "//input[@type=\"mail\"]";
    public static String appsSolicitarAvaliacaoTelefoneInput = "//input[@class=\"form-control phone_mask\"]";
    public static String appsSolicitarAvaliacaoRenavamAndretaInput = "//div[@ng-show=\"ctrl.$api.showFields.renavam\"]//input";
    public static String appsSolicitarAvaliacaoAbrirObservacoesButton = "//button[@class=\"btn btn-xs btn-default\"]";
    public static String appsSolicitarAvaliacaoAreaObservacoesText = "//textarea[@class=\"form-control note-editor ng-pristine ng-untouched ng-valid ng-empty\"]";
    public static String appsSolicitarAvaliacaoPossuiManualDoVeiculoCombobox = "//label[text()=\"Possui manual do veículo?\"]/../select";
    public static String appsSolicitarAvaliacaoVeiculoPossuiGarantiaCombobox = "//label[text()=\"Veículo possui garantia?\"]/../select";
    public static String appsSolicitarAvaliacaoRevisoesCombobox = "//label[text()=\"5 - Todas as revisões feitas em concessionárias?\"]/../select";
    public static String appsSolicitarAvaliacaoForamEfetuadasRevisoesCombobox = "//label[text()=\"Foram efetuadas revisões?\"]/../select";
    public static String appsSolicitarAvaliacaoManualDoProprietarioCombobox = "//label[text()=\"O veículo possui manual do proprietário?\"]/../select";
    public static String appsSolicitarAvaliacaoLivreteCombobox = "//label[text()=\"Livrete\"]/../select";
    public static String appsSolicitarAvaliacaoVeiculoEmGarantiaDeFabricaCombobox = "//label[text()=\"Veículo esta em garantia de fabrica?\"]/../select";
    public static String appsResultadoMarcaButton = "//a[@title=\"FERRARI\"]";
    public static String appsResultadoModeloButton = "//a[@title=\"UNO\"]";
    public static String appsResultadoVersaoButton = "//a[@title=\"CHERY QQ 1.0 MPFI 12V GASOLINA 4P MANUAL (2011)\"]";

    public static LinkedHashMap<String, String> appsSolicitarAvaliacao = createData();
    private static LinkedHashMap<String, String> createData() {
        LinkedHashMap<String, String> ret = new LinkedHashMap<>();
        ret.put(appsSolicitarAvaliacaoTitle, "Titulo solicitar avaliação");
        ret.put(appsTipoAvaliacaoCombobox, "Combobox tipo avaliação");
        ret.put(appsAvaliadorResponsavelCombobox, "Combobox avaliador responsável");
        ret.put(appsNomeDoClienteInput, "Nome do cliente");
        ret.put(appsAnoDeInteresseInput, "Ano de interesse");
        ret.put(appsVeiculoInput, "Veiculo");
        ret.put(appsPrimeiroVeiculoLi, "Primeiro veiculo");
        ret.put(appsBuscarPlacaButton, "Buscar placa");
        ret.put(appsCelularInput, "Celular");
        ret.put(appsPlacaInput, "Placa");
        ret.put(appsSolicitarButton, "Solicitar");
        ret.put(appsObrigatoriedadeTipoDeAvaliacaoText, "Mensagem de obrigatoriedade do campo tipo de avaliação");
        ret.put(appsObrigatoriedadeAvaliadorResponsavelText, "Mensagem de obrigatoriedade do campo avaliador responsável");
        ret.put(appsObrigatoriedadeNomeText, "Mensagem de obrigatoriedade do campo nome");
        ret.put(appsObrigatoriedadeCelularText, "Mensagem de obrigatoriedade do campo celular");
        ret.put(appsObrigatoriedadePlacaText, "Mensagem de obrigatoriedade do campo placa");
        ret.put(appsPlacaInvalidaText, "Mensagem de placa inválida");
        ret.put(appsSolicitarAvaliacoSolicitarButton, "Botaão solicitar, para finalizar solicitacao de avaliação");
        ret.put(appsSolicitarAvaliacaoChaveReservaSelect, "Chave Reserva SIM");
        ret.put(appsSolicitarAvaliacaoManualSelect, "Manual SIM");
        ret.put(appsSolicitarAvaliacaoSolicitaButton, "Solicita");
        ret.put(appsPlacaNaoEncontradaText, "Mensagem de placa não encontrada");
        ret.put(appsSolicitarAvaliacaoCPFInput, "Input cpf para solicitar avaliação");
        ret.put(appsSolicitarAvaliacaoRenavamInput, "Input renavan para solicitar avaliação");
        ret.put(appsSolicitarAvaliacaoExpectativaDoClienteInput, "Input expectativa de preco do cliente para avaliação");
        ret.put(appsSolicitarAvaliacaoOpenFieldObsButton, "Botão para abrir o campo observações");
        ret.put(appsSolicitarAvaliacaoTextObsInput, "Text area observações");
        ret.put(appsSolicitarAvaliacaoNumeroTelefoneInput, "Input numero de telefone");
        ret.put(appsSolicitarAvaliacaoEmailClienteInput, "Input e-mail cliente");
        ret.put(appsSolicitarAvaliacaoAndretaCPFInput, "Input cpf para solciitar avaliacao");
        ret.put(appsSolicitarAvaliacaoTelefoneInput, "Input telefone para solciitar avaliacao");
        ret.put(appsSolicitarAvaliacaoRenavamAndretaInput, "Input renavam para solciitar avaliacao");
        ret.put(appsSolicitarAvaliacaoAbrirObservacoesButton, "Button abrir campo observacoes");
        ret.put(appsSolicitarAvaliacaoAreaObservacoesText, "Text area observacoes");
        ret.put(appsSolicitarAvaliacaoPossuiManualDoVeiculoCombobox, "Combobox possui manual do veiculo");
        ret.put(appsSolicitarAvaliacaoVeiculoPossuiGarantiaCombobox, "Combobox veiculo possui garantia");
        ret.put(appsSolicitarAvaliacaoRevisoesCombobox, "Combobox todas as revisoes foram feitas em concessionarias");
        ret.put(appsSolicitarAvaliacaoManualDoProprietarioCombobox, "Combobox o veiculo possui manual do proprietario");
        ret.put(appsSolicitarAvaliacaoEmailInput, "Input email");
        ret.put(appsSolicitarAvaliacaoForamEfetuadasRevisoesCombobox, "Combobox pergunta foram efetuadas revisoes?");
        ret.put(appsSolicitarAvaliacaoLivreteCombobox, "Combobox livrete");
        ret.put(appsSolicitarAvaliacaoVeiculoEmGarantiaDeFabricaCombobox, "Combobox este veiculo esta em garantia de fabrica ?");
        ret.put(appsResultadoMarcaButton, "FERRARI");
        ret.put(appsResultadoModeloButton, "UNO");
        ret.put(appsResultadoVersaoButton, "CHERY QQ 1.0 MPFI 12V GASOLINA 4P MANUAL (2011)");
        return ret;
    }
}
